# sudo: required

os: linux

language: generic

dist: bionic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t yeongbba/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true yeongbba/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: DockerReactApp-env
  bucket_name: "elasticbeanstalk-ap-northeast-2-924744414500"
  bucket_path: docker-react-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
